/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': 'rgb(var(--on-surface-variant) / <alpha-value>)',
        'outline-variant': '#464555',
        'surface-bright': '#393939',
        'tertiary-fixed-dim': '#ffb785',
        'on-secondary-container': '#00302d',
        'primary-container': 'rgb(var(--primary-container) / <alpha-value>)',
        'on-background': '#e5e2e1',
        'text-secondary': 'rgb(var(--text-secondary) / <alpha-value>)',
        'surface-container': 'rgb(var(--surface-container) / <alpha-value>)',
        primary: 'rgb(var(--primary) / <alpha-value>)',
        'primary-fixed-dim': '#c4c0ff',
        'on-tertiary-fixed-variant': '#713700',
        'on-primary-fixed': '#100069',
        'bg-tertiary': 'rgb(var(--bg-tertiary) / <alpha-value>)',
        'surface-container-high': '#2a2a2a',
        'on-tertiary-fixed': '#301400',
        'on-primary-container': 'rgb(var(--on-primary-container) / <alpha-value>)',
        'surface-tint': '#c4c0ff',
        'on-tertiary-container': '#461f00',
        'on-primary-fixed-variant': '#3622ca',
        error: 'rgb(var(--error) / <alpha-value>)',
        'error-container': '#93000a',
        outline: 'rgb(var(--outline) / <alpha-value>)',
        border: 'rgb(var(--border) / <alpha-value>)',
        'tertiary-fixed': '#ffdcc6',
        'text-heading': 'rgb(var(--text-heading) / <alpha-value>)',
        'inverse-primary': '#4f44e2',
        'surface-container-highest': '#353534',
        'on-primary': 'rgb(var(--on-primary) / <alpha-value>)',
        'surface-container-lowest': '#0e0e0e',
        'tertiary-container': '#db761f',
        'bg-secondary': 'rgb(var(--bg-secondary) / <alpha-value>)',
        surface: '#131313',
        'on-error': '#690005',
        'primary-fixed': '#e3dfff',
        'secondary-fixed-dim': '#5dd9d0',
        'on-error-container': '#ffdad6',
        'on-tertiary': '#502500',
        'on-secondary-fixed-variant': '#00504c',
        'inverse-surface': '#e5e2e1',
        warning: '#FFD93D',
        'secondary-container': '#00a29a',
        'surface-variant': '#353534',
        background: 'rgb(var(--background) / <alpha-value>)',
        'on-surface': '#e5e2e1',
        'on-secondary-fixed': '#00201e',
        secondary: 'rgb(var(--secondary) / <alpha-value>)',
        'secondary-fixed': '#7cf6ec',
        tertiary: 'rgb(var(--tertiary) / <alpha-value>)',
        'text-primary': 'rgb(var(--text-primary) / <alpha-value>)',
        'surface-container-low': '#1c1b1b',
        'inverse-on-surface': '#313030',
        'on-secondary': '#003734',
        'surface-dim': '#131313',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'padding-screen': '16px',
        gutter: '16px',
        base: '8px',
        'max-width': '480px',
      },
      maxWidth: {
        'max-width': '480px',
      },
      fontFamily: {
        button: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
        h2: ['Inter', 'sans-serif'],
        h1: ['Inter', 'sans-serif'],
        'reader-chunk-mobile': ['Inter', 'sans-serif'],
        'reader-chunk': ['Inter', 'sans-serif'],
      },
      fontSize: {
        button: ['15px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        body: ['16px', { lineHeight: '24px', fontWeight: '400' }],
        caption: ['13px', { lineHeight: '18px', fontWeight: '400' }],
        h2: ['20px', { lineHeight: '28px', fontWeight: '600' }],
        h1: ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'reader-chunk-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'reader-chunk': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
